"""
Django settings for jwt_auth project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nbw$iy^w0-tb^)h=r8+p(s7lw#6!x95@2wq7f6z@as$v@mco+3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

# Django REST framework is a powerful and flexible toolkit for building Web APIs.
# Some reasons you might want to use REST framework:
# The Web browsable API is a huge usability win for your developers.
# Authentication policies including optional packages for OAuth1a and OAuth2.
# Serialization that supports both ORM and non-ORM data sources.
# Customizable all the way down - just use regular function-based views if you don't need the more powerful features.
# Extensive documentation, and great community support.




# simplejwt.token_blacklist:
# Simple JWT provides a JSON Web Token authentication backend for the Django REST Framework. 
# It aims to cover the most common use cases of JWTs by offering a conservative set of default features. 
# It also aims to be easily extensible in case a desired feature is not present.
# If the blacklist app is detected in INSTALLED_APPS, Simple JWT will add any generated refresh or sliding tokens to a list of outstanding tokens. 
# It will also check that any refresh or sliding token does not appear in a blacklist of tokens before it considers it as valid.
# The Simple JWT blacklist app implements its outstanding and blacklisted token lists using two models: 
# OutstandingToken and BlacklistedToken. Model admins are defined for both of these models. 
# To add a token to the blacklist, find its corresponding OutstandingToken record in 
# the admin and use the admin again to create a BlacklistedToken record that points to the OutstandingToken record.


# CORSHEADERS-Cross-Origin Resource Sharing is a mechanism for allowing clients to interact with APIs that are hosted on a different domain. 
# CORS works by requiring the server to include a specific set of headers that allow a browser to determine if and when cross-domain requests should be allowed. 
# The best way to deal with CORS in REST framework is to add the required response headers in middleware. 
# This ensures that CORS is supported transparently, without having to change any behavior in your views. 
# Adam Johnson maintains the django-cors-headers package, which is known to work correctly with REST framework APIs.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jwt_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jwt_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
